dependencies:
    - OpenZeppelin/openzeppelin-contracts@3.4.0
    - smartcontractkit/chainlink-brownie-contracts@1.0.2
compiler:
  solc:
    remappings: 
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
wallets:
  from_key: ${PRIVATE_KEY}
  client_wallet: '0x7dca13b99A59e1Eb2a4586efDFE71a1840111930'
networks:
    default: development
    rinkeby:
      vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
      link_token: '0x01be23585060835e02b77ef475b0cc51aa1e0709'
      keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
